services:
  mongo:
    image: 'mongo:6'
    restart: unless-stopped
    volumes:
      - 'mongo-data:/data/db'
  server:
    build:
      context: .
      dockerfile: ./apps/OpenSignServer/Dockerhubfile
    restart: unless-stopped
    depends_on:
      - mongo
    expose:
      - '8080'
    environment:
      PUBLIC_URL: 'https://sign.medcei.com'
      SERVER_URL: 'https://api-sign.medcei.com/app'
      MONGODB_URI: 'mongodb://mongo:27017/OpenSignDB'
      MASTER_KEY: 9fd4sdf9sdf9sdf9sdf9sdf9
      PARSE_MOUNT: /app
      APP_ID: opensign
      USE_LOCAL: 'true'
      SMTP_ENABLE: 'true'
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=coolify'
      - 'traefik.http.routers.opensign-api.rule=Host(`api-sign.medcei.com`)'
      - 'traefik.http.routers.opensign-api.entrypoints=https'
      - 'traefik.http.routers.opensign-api.tls=true'
      - 'traefik.http.services.opensign-api.loadbalancer.server.port=8080'
    networks:
      - default
      - coolify
  client:
    build:
      context: .
      dockerfile: ./apps/OpenSign/Dockerhubfile
    restart: unless-stopped
    depends_on:
      - server
    expose:
      - '3000'
    environment:
      PUBLIC_URL: 'https://sign.medcei.com'
      REACT_APP_SERVERURL: 'https://api-sign.medcei.com/app'
      REACT_APP_APPID: opensign
      GENERATE_SOURCEMAP: 'false'
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=coolify'
      - 'traefik.http.routers.opensign-web.rule=Host(`sign.medcei.com`)'
      - 'traefik.http.routers.opensign-web.entrypoints=https'
      - 'traefik.http.routers.opensign-web.tls=true'
      - 'traefik.http.services.opensign-web.loadbalancer.server.port=3000'
    networks:
      - default
      - coolify
volumes:
  mongo-data: null
networks:
  coolify:
    external: true
